apiVersion: v1
kind: Service
metadata:
  name: middleware-service
spec:
  selector:
    app: middleware
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
  type: NodePort
